apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: europe-west8-docker.pkg.dev/nestjs-k8s-415221/auth/production
          name: auth
          env:
            - name: TCP_PORT
              value: '3002'
            - name: HTTP_PORT
              value: '3003'
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectionString
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtSecretKey
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: jwtExpiration
          ports:
            - containerPort: 3002
            - containerPort: 3003
